use_frameworks!

platform :ios, '10.0'

target 'WGTPushNotification_Example' do
  pod 'WGTPushNotification', :path => '../'

  target 'WGTPushNotification_Tests' do
    inherit! :search_paths

    
  end
end
